CREATE DATABASE API_CURSOS;

USE API_CURSOS;

CREATE TABLE ALUNOS
(
    ALUNOID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    IDADE INT CHECK (IDADE > 0),
    EMAIL VARCHAR(100) UNIQUE,
    DATAMATRICULA DATETIME
);

CREATE TABLE CURSOS
(
    CURSOID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(250),
    CARGAHORARIA INT CHECK (CARGAHORARIA > 0)
);

CREATE TABLE MATRICULAS
(
    MATRICULAID INT IDENTITY(1,1) PRIMARY KEY,
    ALUNOID INT NOT NULL,
    CURSOID INT NOT NULL,
    DATAMATRICULA DATETIME,
    
    FOREIGN KEY (ALUNOID) REFERENCES ALUNOS(ALUNOID),
    FOREIGN KEY (CURSOID) REFERENCES CURSOS(CURSOID)
);
